name: Build FanControl.LianLi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Restore dependencies
        run: dotnet restore src/FanControl.LianLiPlugin.sln

      - name: Build solution
        run: dotnet build src/FanControl.LianLiPlugin.sln --configuration Release

      - name: Publish binaries
        if: success()
        run: |
          mkdir build
          cp src/bin/Release/* build/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: FanControl.LianLiPlugin
          path: build/
